media: Revert "[media] Terratec Cinergy S2 USB HD Rev.2"
This reverts commit 1fdd4ea61f11ee4a1ead90ed802ece6662537e3f.

drivers/media/dvb/dvb-usb/dw2102.c:1478:18: error: ‘USB_PID_TEVII_S421’ undeclared here (not in a function)
drivers/media/dvb/dvb-usb/dw2102.c:1479:18: error: ‘USB_PID_TEVII_S632’ undeclared here (not in a function)

Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>