m68k: Make sure NR_IRQS is never zero
When compiling an MMU kernel without any platform support, e.g.
"MMU=y allnoconfig":

    echo CONFIG_MMU=y > allno.config
    make KCONFIG_ALLCONFIG=1 allnoconfig

NR_IRQS is zero, causing a build failure:

    kernel/irq/irqdesc.c:593:3: error: array index in initializer exceeds array bounds
      593 |  [0 ... NR_IRQS-1] = {
	  |   ^
    kernel/irq/irqdesc.c:593:3: note: (near initialization for ‘irq_desc’)
    kernel/irq/irqdesc.c:593:22: warning: excess elements in array initializer
      593 |  [0 ... NR_IRQS-1] = {
	  |                      ^
    kernel/irq/irqdesc.c:593:22: note: (near initialization for ‘irq_desc’)

Fix this by setting the default value of NR_IRQS to 8, which is the
mininum number of interrupts on any m68k CPU (the DIP48 variant of the
MC68008 has tied IPL0 and IPL2 together, but that does not impact the
range).

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Link: https://lore.kernel.org/71db70dc27b46e5326518cd23cb94fa6bee172fe.1730805216.git.geert@linux-m68k.org