Revert "usb: host/sl811-hcd: fix sparse warning"
This reverts commit 9c1724a76f9c86c1fbd19768cbcb7bbed52b7861.

Commit 9c1724a76f9c results in the following error when compiling
x86_64:allyesconfig.

sl811_cs.c:(.text+0x1d3cb72): undefined reference to `sl811h_driver'

Fixes: 9c1724a76f9c ("usb: host/sl811-hcd: fix sparse warning")
Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>