media: wl128x: fix a clang warning
Clang-16 produces this warning, which is fatal with CONFIG_WERROR:

	../drivers/media/radio/wl128x/fmdrv_common.c:1237:19: error: variable 'cmd_cnt' set but not used [-Werror,-Wunused-but-set-variable]
	        int ret, fw_len, cmd_cnt;
	                         ^
	1 error generated.

What happens is that cmd_cnt tracks the amount of firmware data packets
were transfered, which is printed only when debug is used.

Switch to use the firmware count, as the message is all about reporting
a partial firmware transfer.

Link: https://lore.kernel.org/linux-media/6badd27ebfa718d5737f517f18b29a3e0f6e43f8.1687981726.git.mchehab@kernel.org

Signed-off-by: Mauro Carvalho Chehab <mchehab@kernel.org>