ARM: dove: Drop a write-only variable
This fixes a W=1 build error:

	arch/arm/mach-dove/common.c: In function ‘dove_clk_init’:
	arch/arm/mach-dove/common.c:85:40: error: variable ‘gephy’ set but not used [-Werror=unused-but-set-variable]
	   85 |         struct clk *xor0, *xor1, *ge, *gephy;
	      |                                        ^~~~~

Fixes: 4a8738b10adf ("ARM: dove: add clock gating control")
Signed-off-by: Uwe Kleine-König <u.kleine-koenig@baylibre.com>
Reviewed-by: Andrew Lunn <andrew@lunn.ch>
Signed-off-by: Gregory CLEMENT <gregory.clement@bootlin.com>