HID: intel-ish-hid: fix module device-id handling
A late addititon to the intel-ish-hid framework caused a build failure
with clang, and introduced an ABI to the module loader that stops working
if any driver ever needs to bind to more than one UUID:

drivers/hid/intel-ish-hid/ishtp-fw-loader.c:1067:4: error: initializer element is not a compile-time constant

Change the ishtp_device_id to have correct documentation and a driver_data
field like all the other ones, and change the drivers to use the ID table
as the primary identification in a way that works with all compilers
and avoids duplciating the identifiers.

Fixes: 4cee49938c2f ("platform/x86: isthp_eclite: only load for matching devices")
Fixes: 4809cb62e6f8 ("platform/chrome: chros_ec_ishtp: only load for matching devices")
Fixes: bed702a3cba1 ("HID: intel-ish-hid: hid-client: only load for matching devices")
Fixes: a975bd6ca318 ("HID: intel-ish-hid: fw-loader: only load for matching devices")
Fixes: e9464e01fa98 ("HID: intel-ish-hid: use constants for modaliases")
Fixes: ba08e5fbb192 ("HID: intel-ish-hid: add support for MODULE_DEVICE_TABLE()")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reviewed-by: Hans de Goede <hdegoede@redhat.com>
[jkosina@suse.cz: fix ecl_ishtp_cl_driver.id initialization]
[jkosina@suse.cz: fix conflict with already fixed kerneldoc]
Signed-off-by: Jiri Kosina <jkosina@suse.cz>