staging:iio:adis16260: Select adislib
Commit dcb2c2f6 ("staging:iio:adis16260: Use adis library") switched over the
adis16260 driver to use the common adis library but neglected to update the
Kconfig entry to reflect the change.

This leads to the following compile error if no other driver selects the adis
library:

	drivers/built-in.o: In function `adis16260_write_frequency':
		adis16260_core.c:(.text+0x5a83bf): undefined reference to `adis_write_reg_8'
	drivers/built-in.o: In function `adis16260_read_frequency':
		adis16260_core.c:(.text+0x5a8433): undefined reference to `adis_read_reg_16'
	drivers/built-in.o: In function `adis16260_write_raw':
		adis16260_core.c:(.text+0x5a8538): undefined reference to `adis_write_reg_16'
		adis16260_core.c:(.text+0x5a856b): undefined reference to `adis_write_reg_16'
	drivers/built-in.o: In function `adis16260_read_raw':
		adis16260_core.c:(.text+0x5a85d3): undefined reference to `adis_single_conversion'
		adis16260_core.c:(.text+0x5a873e): undefined reference to `adis_read_reg_16'
		adis16260_core.c:(.text+0x5a87fb): undefined reference to `adis_read_reg_16'
	drivers/built-in.o: In function `adis16260_probe':
		adis16260_core.c:(.devinit.text+0x5c6b8): undefined reference to `adis_init'
		adis16260_core.c:(.devinit.text+0x5c799): undefined reference to `adis_initial_startup'
	drivers/built-in.o: In function `adis16260_remove':
		adis16260_core.c:(.devexit.text+0x9943): undefined reference to `adis_write_reg_16'

This patch updates the adis16260 Kconfig entry to select the adis library.

Reported-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
Signed-off-by: Jonathan Cameron <jic23@kernel.org>