extcon: max3355: include mod_devicetable.h
Another driver turned up that is missing linux/mod_devicetable.h after
the device IDs are split out from linux/platform_device.h:

drivers/extcon/extcon-max3355.c:127:34: error: array type has incomplete element type 'struct of_device_id'
 static const struct of_device_id max3355_match_table[] = {

Fixes: d731bbf263f2 ("headers: separate linux/mod_devicetable.h from linux/platform_device.h")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>