Revert "[SCSI] cnic: fix error: implicit declaration of function ‘__symbol_get’"
This reverts commit 0b3021efe1ed347e5ed1b497a3030e68cb932099.

All the commit did was add a second #include of <linux/module.h> which is
the wrong fix.

Signed-off-by: James Bottomley <James.Bottomley@HansenPartnership.com>