powerpc/pseries: Define __u{8,32} types in papr_hvpipe_hdr struct
Fix the the following build errors with CONFIG_UAPI_HEADER_TEST:

./usr/include/asm/papr-hvpipe.h:16:9: error: unknown type name 'u8'
   16 |         u8 version;
./usr/include/asm/papr-hvpipe.h:17:9: error: unknown type name 'u8'
   17 |         u8 reserved[3];
./usr/include/asm/papr-hvpipe.h:18:9: error: unknown type name 'u32'
   18 |         u32 flags;
./usr/include/asm/papr-hvpipe.h:19:9: error: unknown type name 'u8'
   19 |         u8 reserved2[40];

Fixes: cd53f7e8e5602 ("powerpc/pseries: Define papr-hvpipe ioctl")
Reported-by: Venkat Rao Bagalkote <venkat88@linux.ibm.com>
Signed-off-by: Haren Myneni <haren@linux.ibm.com>
Tested-by: Venkat Rao Bagalkote <venkat88@linux.ibm.com>
Signed-off-by: Madhavan Srinivasan <maddy@linux.ibm.com>
Link: https://patch.msgid.link/20250922091108.1483970-1-haren@linux.ibm.com