parisc: avoid c23 'nullptr' idenitifier
Starting in c23, this is a reserved keyword, so in the future, using it
will start causing build failures:

arch/parisc/math-emu/frnd.c:36:23: error: expected ';', ',' or ')' before 'nullptr'

Since I can't think of a good replacement name, add a leading underscore
to the function argument to avoid this namespace conflict. Apparently
all of these arguments are unused.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Helge Deller <deller@gmx.de>