tty/amiserial: Add missing argument for tty_unlock()
commit e8abbe2e1ced269956e66bee6f76a8c17ed2e8ae ("tty_lock: Localise the lock")
missed that 6089bdf6c95fed71ed8c1b1881fb45eba6d01072 ("drivers/tty/amiserial.c:
add missing tty_unlock") just added a new caller of tty_unlock():

drivers/tty/amiserial.c: In function ‘set_serial_info’:
drivers/tty/amiserial.c:1077: error: too few arguments to function ‘tty_unlock’

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>