Revert "ARM: dts: hix5hd2: add wdg node"
This reverts commit eb855b753665ce2b5cfadab034e35c9d3e5dcd9b.

"ARM: dts: hix5hd2: add wdg node" causes a build breakage due to
an undefined constatns:

Error: arch/arm/boot/dts/hisi-x5hd2.dtsi:374.22-23 syntax error

(Don't you just looove the dtc error messages? They are so informative!)

Signed-off-by: Olof Johansson <olof@lixom.net>