Revert "pktgen: Allow configuration of IPv6 source address range"
This reverts commit 149e457d8ffe7e95c3c60bc11e361d399ed5ea17.

It causes build failures on 32-bit, for example:

   net/core/pktgen.o: In function `mod_cur_headers':
>> pktgen.c:(.text.mod_cur_headers+0xba0): undefined reference to `__umoddi3'

Signed-off-by: David S. Miller <davem@davemloft.net>