[IA64] fix build error - arch/ia64/kernel/perfmon.c
arch/ia64/kernel/perfmon.c:621: error: duplicate 'static'

Introduced by commit e3762c7ae116350861053e82fe282c3e98caf83e

    pass default dentry_operations to mount_pseudo()

Signed-off-by: Tony Luck <tony.luck@intel.com>