net: netcp: correct netcp_get_stats function signature
Commit: 0e7014ad23bd - net: make ndo_get_stats64 a void function
and
Commit: 59f059675ac0 - net: netcp: store network statistics in 64 bits.

The commit 59f059675ac0 adds ndo_get_stats64 function as per old
signature which causes compilation error:

drivers/net/ethernet/ti/netcp_core.c:1951:28: error:
initialization from incompatible pointer type
  .ndo_get_stats64        = netcp_get_stats,

Hence correct netcp_get_stats function signature as per
the latest definition.

Signed-off-by: Keerthy <j-keerthy@ti.com>
Fixes: 59f059675ac00bf5 ("net: netcp: store network statistics in 64 bits")
Signed-off-by: David S. Miller <davem@davemloft.net>