fpga: versal: remove incorrect of_match_ptr annotation
Building with W=1 shows a warning about versal_fpga_of_match being unused when
CONFIG_OF is disabled:

    drivers/fpga/versal-fpga.c:62:34: error: unused variable 'versal_fpga_of_match' [-Werror,-Wunused-const-variable]

Acked-by: Xu Yilun <yilun.xu@intel.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20250225163510.4168911-1-arnd@kernel.org
Signed-off-by: Xu Yilun <yilun.xu@linux.intel.com>