regulator: adp5055: remove duplicate device table
When building with -Wunused-const-variable, gcc points out an
device table that is not referenced anywhere:

drivers/regulator/adp5055-regulator.c:346:34: error: unused variable 'adp5055_dt_ids' [-Werror,-Wunused-const-variable]
  346 | static const struct of_device_id adp5055_dt_ids[] = {
      |                                  ^~~~~~~~~~~~~~

The contents are the same as the second table in that file, so
just remove this copy.

Fixes: 770c4be459e2 ("regulator: adp5055: Add driver for adp5055")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://patch.msgid.link/20250410141006.866813-1-arnd@kernel.org
Signed-off-by: Mark Brown <broonie@kernel.org>