Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
This reverts commit 97fc686ae7288df7b06cd880a166c1ebd4095357, which
causes a build failure:

drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer