platform: cznic: turris-omnia-mcu: Depend on OF
Add depend on OF, otherwise the compilation fails with
  error: no member named 'of_gpio_n_cells' in 'struct gpio_chip'
  error: no member named 'of_xlate' in 'struct gpio_chip'

Fixes: 5c3dd05c58ce ("platform: cznic: turris-omnia-mcu: Add support for MCU connected GPIOs")
Reported-by: kernel test robot <lkp@intel.com>
Closes: https://lore.kernel.org/oe-kbuild-all/202407031646.trNSwajF-lkp@intel.com/
Signed-off-by: Marek Behún <kabel@kernel.org>
Link: https://lore.kernel.org/r/20240708114002.4285-2-kabel@kernel.org
Signed-off-by: Arnd Bergmann <arnd@arndb.de>