Revert "drm/msm/mdp5: provide dynamic bandwidth management"
This reverts commit 1008101edd7664844079d26f6c7b6ffb3eccc89e.

Breaks armv7 build

  ERROR: modpost: "__aeabi_ldivmod" [drivers/gpu/drm/msm/msm.ko] undefined!

Signed-off-by: Rob Clark <robdclark@chromium.org>