Revert "net: dccp: initialize (addr,port) listening hashtable"
This reverts commit de06e2100fd7c0e4fb3ff907190eca9f5b3ede42.

Cause build failures when DCCP is modular.

ERROR: "inet_hashinfo2_init" [net/dccp/dccp.ko] undefined!

Signed-off-by: David S. Miller <davem@davemloft.net>