fbdev/sgivwfb: fix compilation error in sgivwfb_mmap()
Commit efb213d5ba76b1ea7f55569966614083c3e42637 ("fbdev/sgivwfb: use
vm_iomap_memory()") changed sgivwfb_mmap() to use the new
vm_iomap_memory() function. The commit introduced the following
compilation error:

drivers/video/sgivwfb.c:716:9: note: each undeclared identifier is
reported only once for each function it appears in

This patch fixes the error.

Signed-off-by: Tomi Valkeinen <tomi.valkeinen@ti.com>