[IA64] build broken for ia64 simserial.c
TTY layer buffering revamp broke ia64 in commit
 a86ade2d09aa60683e3478b5cb0f77e3b9b4c4c7

  CC      arch/ia64/hp/sim/simserial.o
arch/ia64/hp/sim/simserial.c: In function `receive_chars':
arch/ia64/hp/sim/simserial.c:170: error: structure has no member named `flip'
 ... and so on ...
make[1]: *** [arch/ia64/hp/sim/simserial.o] Error 1

Patch from Andreas Schwab.

Signed-off-by: Tony Luck <tony.luck@intel.com>