tty: serial: export serial_8250_warn_need_ioport
The newly added function is used from a loadable module, so it has
to be exported the same way as the other function in this file:

ERROR: modpost: "serial_8250_warn_need_ioport" [drivers/tty/serial/8250/8250_pci.ko] undefined!

Fixes: 3f2d864734ce ("tty: serial: handle HAS_IOPORT dependencies")
Reviewed-by: Niklas Schnelle <schnelle@linux.ibm.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>