drm/sti: restore mode_fixup callback
Commit dcc243c0cd1e removed the mode_fixup because it was empty,
but 188410ad3ea0 modified it to call drm_mode_set_crtcinfo()
instead.

Both commits are correct, but the merge of the two kept the nonempty
version without the reference to it, as shown by the gcc warning:

 drm/sti/sti_crtc.c:54:13: error: 'sti_crtc_mode_fixup' defined but not used

This restores the callback pointer to fix the merge.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reverts: dcc243c0cd1e ("drm/sti: removed optional dummy crtc mode_fixup function.")
Fixes: 188410ad3ea0 ("drm/sti: set CRTC modesetting parameters")
Fixes: d38e337733b6 ("Merge branch '2016-02-26-st-drm-next' of http://git.linaro.org/people/benjamin.gaignard/kernel into drm-next")
Acked-by: Vincent ABRIOU <vincent.abriou@st.com>
Signed-off-by: Dave Airlie <airlied@redhat.com>