ARM: S5P: Fix export.h inclusion
Commit 1db68cbba633 ("Merge branch 'modsplit-Oct31 2011'...")
breaks build like following and this fixes it to add inclusion
<linux/export.h>.

arch/arm/plat-s5p/sysmmu.c:302: error: 'THIS_MODULE' undeclared here (not in a function)

Signed-off-by: Kukjin Kim <kgene.kim@samsung.com>