staging: ccree: remove unused function argument
"gcc -Wunused" warns about one argument being assigned but not used:

drivers/staging/ccree/ssi_cipher.c: In function 'ssi_blkcipher_complete':
drivers/staging/ccree/ssi_cipher.c:747:41: error: parameter 'info' set but not used [-Werror=unused-but-set-parameter]

We can simply drop that argument here and in its callers.

Fixes: e5b3707772b5 ("staging: ccree: add skcipher support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
[ gby: rebased patch on latest revision and chopped >80 chars long lines ]
Signed-off-by: Gilad Ben-Yossef <gilad@benyossef.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>